package com.ashvin.projects.learn_mongodb.repository;

import com.ashvin.projects.learn_mongodb.entity.Order;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;

import java.util.List;

public interface OrderRepository extends MongoRepository< Order, String> {

    // automatically query will be generated by spring data mongodb based on the method name
    List<Order> findByStatusAndQuantityGreaterThan(String status,Integer quantity);
    List<Order> findByStatusAndQuantityGreaterThanOrderByCreatedAtDesc(String status,Integer quantity);

    @Query("{ 'status': ?0, 'totalPrice': { $gte: ?1 } }")
    // query will not be generated and this will be used as it is
    List<Order> findOrdersByStatusAboveAndPrice(String status, double minPrice);

    List<Order> findByAddressCity(String city);

    @Query(value = "{ 'address.city': ?0 }",fields = "{'_id' : 1 ,'quantity': 1}")
    List<Order> findByCity(String city);
}
