spring:
  data:
    mongodb:
      auto-index-creation: true
      # authSource = admin tells MongoDB to look for the user credentials (username and password)
      # in the admin database, not in the ecommerce database
      uri: mongodb://admin:password@localhost:27017/ecommerce?authSource=admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG